#ifndef CONST_HPP
#define CONST_HPP

const int BROKER_FRONTEND_PORT = 5555;
const int BROKER_BACKEND_PORT = 5556;
const int BROKER_SERVICE_NAME_REGISTRY_LOOKUP_PORT = 5557;
const int BROKER_SERVICE_NAME_REGISTRY_ADD_PORT = 5558;

#endif // CONST_HPP